### ISSUE TITLE
Dino game using python

### ISSUE THREAD

**Issue by ojhapiyush** [Ghosty-deep/Game-deployement#3]
I would like to add code for dino game in python. Could it be assigned under hacktoberfest.

**Comment by Ghosty-deep** [comment]
JUST MADE A PULL REQUEST OF UR GAME PROTOTYPE.
AFTER VIEWING IT WILL BE MERGED.

**Comment by Ghosty-deep** [comment]
Hope so you got the things,made ur prototype pull request to repository.
